#ifndef __VIDEO_DEMO_H
#define __VIDEO_DEMO_H 
enum DEMO_ENUM
{
    JPG0_ENCODE_DEMO_FROM_VPP_DATA0,
    JPG0_ENCODE_DEMO_FROM_VPP_DATA1,
    H264_ENCODE_DEMO_FROM_VPP_DATA0,
    H264_ENCODE_DEMO_FROM_VPP_DATA1,
    H264_ENCODE_DEMO_FROM_VPP_DATA0_SAVE_TO_SD,
    JPG_DEMO_FROM_USB,
    USB_THUMB_DEMO,
    VPP_THUMB_DEMO,
    TAKEPHOTO_DEMO,
    DEMO_MAX,
};

void video_demo_thread(enum DEMO_ENUM which);

#endif