#ifndef __PIN_PARAM_H
#define __PIN_PARAM_H
#include "project_config.h"
#include "tx_platform.h"
//这个是io配置的宏,后续sdk是通过这个宏去获取对应的io值,没有配置,则设置为0xff
//坚守的原则,增加的宏增加到最后,不能插入到开头或者中间,也不能更换宏的位置,否则不同sdk之间参数区不匹配
//所以SDK默认的宏最好不要动,用户自定义的话,也要保持该原则
//为了兼容旧版的pin_function,这里的宏定义命名都是MACRO_PIN_DEFINE(XXXX)(XXXX是之前宏的名称)
//新增的自定义宏依然采用PARAM_开头,后面的宏则采用自定义,默认都是往后增加即可保持新版本和旧版本兼容
//如果需要pin_funciton在PIN_FROM_PARAM定义与不定义都兼容的话,则这里添加一个宏后,pin_name.h也要添加对应无PARAM_前缀的宏,否则编译报错
//如果不需要兼容,则直接在这里添加即可
#ifdef PIN_FROM_PARAM
enum pin_cfg
{
    //串口
    MACRO_PIN_DEFINE(PIN_UART0_TX),
    MACRO_PIN_DEFINE(PIN_UART0_RX),
    MACRO_PIN_DEFINE(PIN_UART1_TX),
    MACRO_PIN_DEFINE(PIN_UART1_RX),
    MACRO_PIN_DEFINE(PIN_UART4_TX),
    MACRO_PIN_DEFINE(PIN_UART4_RX),
    MACRO_PIN_DEFINE(PIN_UART5_TX),
    MACRO_PIN_DEFINE(PIN_UART5_RX),
    MACRO_PIN_DEFINE(PIN_UART6_TX),
    MACRO_PIN_DEFINE(PIN_UART6_RX),

    //gmac
    MACRO_PIN_DEFINE(PIN_GMAC_RMII_REF_CLKIN),
    MACRO_PIN_DEFINE(PIN_GMAC_RMII_RXD0),
    MACRO_PIN_DEFINE(PIN_GMAC_RMII_RXD1),
    MACRO_PIN_DEFINE(PIN_GMAC_RMII_TXD0),
    MACRO_PIN_DEFINE(PIN_GMAC_RMII_TXD1),
    MACRO_PIN_DEFINE(PIN_GMAC_RMII_CRS_DV),
    MACRO_PIN_DEFINE(PIN_GMAC_RMII_TX_EN),
    MACRO_PIN_DEFINE(PIN_GMAC_RMII_MDIO),
    MACRO_PIN_DEFINE(PIN_GMAC_RMII_MDC),

    //sdio
    MACRO_PIN_DEFINE(PIN_SDCLK),
    MACRO_PIN_DEFINE(PIN_SDCMD),
    MACRO_PIN_DEFINE(PIN_SDDAT0),
    MACRO_PIN_DEFINE(PIN_SDDAT1),
    MACRO_PIN_DEFINE(PIN_SDDAT2),
    MACRO_PIN_DEFINE(PIN_SDDAT3),


    //spi
    MACRO_PIN_DEFINE(PIN_SPI0_CS),
    MACRO_PIN_DEFINE(PIN_SPI0_CLK),
    MACRO_PIN_DEFINE(PIN_SPI0_IO0),
    MACRO_PIN_DEFINE(PIN_SPI0_IO1),
    MACRO_PIN_DEFINE(PIN_SPI0_IO2),
    MACRO_PIN_DEFINE(PIN_SPI0_IO3),

    MACRO_PIN_DEFINE(PIN_SPI1_CS),
    MACRO_PIN_DEFINE(PIN_SPI1_CLK),
    MACRO_PIN_DEFINE(PIN_SPI1_IO0),
    MACRO_PIN_DEFINE(PIN_SPI1_IO1),
    MACRO_PIN_DEFINE(PIN_SPI1_IO2),
    MACRO_PIN_DEFINE(PIN_SPI1_IO3),

    MACRO_PIN_DEFINE(PIN_SPI2_CS),
    MACRO_PIN_DEFINE(PIN_SPI2_CLK),
    MACRO_PIN_DEFINE(PIN_SPI2_IO0),
    MACRO_PIN_DEFINE(PIN_SPI2_IO1),
    MACRO_PIN_DEFINE(PIN_SPI2_IO2),
    MACRO_PIN_DEFINE(PIN_SPI2_IO3),
    
    //pdm
    MACRO_PIN_DEFINE(PIN_PDM_MCLK),
    MACRO_PIN_DEFINE(PIN_PDM_DATA),

    //led
    MACRO_PIN_DEFINE(PIN_LED_SEG0),
    MACRO_PIN_DEFINE(PIN_LED_SEG1),
    MACRO_PIN_DEFINE(PIN_LED_SEG2),
    MACRO_PIN_DEFINE(PIN_LED_SEG3),
    MACRO_PIN_DEFINE(PIN_LED_SEG4),
    MACRO_PIN_DEFINE(PIN_LED_SEG5),
    MACRO_PIN_DEFINE(PIN_LED_SEG6),
    MACRO_PIN_DEFINE(PIN_LED_SEG7),

    MACRO_PIN_DEFINE(PIN_LED_COM0),
    MACRO_PIN_DEFINE(PIN_LED_COM1),
    MACRO_PIN_DEFINE(PIN_LED_COM2),

    //iic
    MACRO_PIN_DEFINE(PIN_IIC1_SCL),
    MACRO_PIN_DEFINE(PIN_IIC1_SDA),

    MACRO_PIN_DEFINE(PIN_IIC2_SCL),
    MACRO_PIN_DEFINE(PIN_IIC2_SDA),

    //timer
    MACRO_PIN_DEFINE(PIN_PWM_CHANNEL_0),
    MACRO_PIN_DEFINE(PIN_PWM_CHANNEL_1),
    MACRO_PIN_DEFINE(PIN_PWM_CHANNEL_2),
    MACRO_PIN_DEFINE(PIN_PWM_CHANNEL_3),

    MACRO_PIN_DEFINE(PIN_CAPTURE_CHANNEL_0),
    MACRO_PIN_DEFINE(PIN_CAPTURE_CHANNEL_1),
    MACRO_PIN_DEFINE(PIN_CAPTURE_CHANNEL_2),

    //dvp
    MACRO_PIN_DEFINE(PIN_DVP_HSYNC),
    MACRO_PIN_DEFINE(PIN_DVP_VSYNC),
    MACRO_PIN_DEFINE(PIN_DVP_PCLK),
    MACRO_PIN_DEFINE(PIN_DVP_MCLK),
    MACRO_PIN_DEFINE(PIN_DVP_DATA0),
    MACRO_PIN_DEFINE(PIN_DVP_DATA1),
    MACRO_PIN_DEFINE(PIN_DVP_DATA2),
    MACRO_PIN_DEFINE(PIN_DVP_DATA3),
    MACRO_PIN_DEFINE(PIN_DVP_DATA4),
    MACRO_PIN_DEFINE(PIN_DVP_DATA5),
    MACRO_PIN_DEFINE(PIN_DVP_DATA6),
    MACRO_PIN_DEFINE(PIN_DVP_DATA7),
    MACRO_PIN_DEFINE(PIN_DVP_DATA8),
    MACRO_PIN_DEFINE(PIN_DVP_DATA9),
    MACRO_PIN_DEFINE(PIN_DVP_DATA10),
    MACRO_PIN_DEFINE(PIN_DVP_DATA11),

    //mipi csi
    MACRO_PIN_DEFINE(PIN_MIPI_CSI0_CLKN),
    MACRO_PIN_DEFINE(PIN_MIPI_CSI0_CLKP),
    MACRO_PIN_DEFINE(PIN_MIPI_CSI0_D0N),
    MACRO_PIN_DEFINE(PIN_MIPI_CSI0_D0P),
    MACRO_PIN_DEFINE(PIN_MIPI_CSI0_D1N_CSI1_D0N),
    MACRO_PIN_DEFINE(PIN_MIPI_CSI0_D1P_CSI1_D0P),
    MACRO_PIN_DEFINE(PIN_MIPI_CSI1_CLKN),
    MACRO_PIN_DEFINE(PIN_MIPI_CSI1_CLKP),

    //mipi dsi
    MACRO_PIN_DEFINE(PIN_MIPI_DSI_CLKN),
    MACRO_PIN_DEFINE(PIN_MIPI_DSI_CLKP),
    MACRO_PIN_DEFINE(PIN_MIPI_DSI_D0N),
    MACRO_PIN_DEFINE(PIN_MIPI_DSI_D0P),
    MACRO_PIN_DEFINE(PIN_MIPI_DSI_D1N),
    MACRO_PIN_DEFINE(PIN_MIPI_DSI_D1P),
    MACRO_PIN_DEFINE(PIN_MIPI_DSI_D2N),
    MACRO_PIN_DEFINE(PIN_MIPI_DSI_D2P),
    MACRO_PIN_DEFINE(PIN_MIPI_DSI_D3N),
    MACRO_PIN_DEFINE(PIN_MIPI_DSI_D3P),

    //lcdc
    MACRO_PIN_DEFINE(LCD_VS_CS),
    MACRO_PIN_DEFINE(LCD_HS_DC),
    MACRO_PIN_DEFINE(LCD_DE_ERD),
    MACRO_PIN_DEFINE(LCD_DOTCLK_RWR),
    MACRO_PIN_DEFINE(LCD_TE),
    MACRO_PIN_DEFINE(LCD_D0),
    MACRO_PIN_DEFINE(LCD_D1),
    MACRO_PIN_DEFINE(LCD_D2),
    MACRO_PIN_DEFINE(LCD_D3),
    MACRO_PIN_DEFINE(LCD_D4),
    MACRO_PIN_DEFINE(LCD_D5),
    MACRO_PIN_DEFINE(LCD_D6),
    MACRO_PIN_DEFINE(LCD_D7),
    MACRO_PIN_DEFINE(LCD_D8),
    MACRO_PIN_DEFINE(LCD_D9),
    MACRO_PIN_DEFINE(LCD_D10),
    MACRO_PIN_DEFINE(LCD_D11),
    MACRO_PIN_DEFINE(LCD_D12),
    MACRO_PIN_DEFINE(LCD_D13),
    MACRO_PIN_DEFINE(LCD_D14),
    MACRO_PIN_DEFINE(LCD_D15),
    MACRO_PIN_DEFINE(LCD_D16),
    MACRO_PIN_DEFINE(LCD_D17),
    MACRO_PIN_DEFINE(LCD_D18),
    MACRO_PIN_DEFINE(LCD_D19),
    MACRO_PIN_DEFINE(LCD_D20),
    MACRO_PIN_DEFINE(LCD_D21),
    MACRO_PIN_DEFINE(LCD_D22),
    MACRO_PIN_DEFINE(LCD_D23),

    //sdh
    MACRO_PIN_DEFINE(PIN_SDH_CLK),
    MACRO_PIN_DEFINE(PIN_SDH_CMD),
    MACRO_PIN_DEFINE(PIN_SDH_DAT0),
    MACRO_PIN_DEFINE(PIN_SDH_DAT1),
    MACRO_PIN_DEFINE(PIN_SDH_DAT2),
    MACRO_PIN_DEFINE(PIN_SDH_DAT3),
    MACRO_PIN_DEFINE(PIN_SDH_CLK_DRI_STRENGTH),

    //para_in
    MACRO_PIN_DEFINE(PIN_BT_HSYNC),
    MACRO_PIN_DEFINE(PIN_BT_VSYNC),
    MACRO_PIN_DEFINE(PIN_BT_PCLK),
    MACRO_PIN_DEFINE(PIN_BT_BLANK),
    MACRO_PIN_DEFINE(PIN_BT_DATA0),
    MACRO_PIN_DEFINE(PIN_BT_DATA1),
    MACRO_PIN_DEFINE(PIN_BT_DATA2),
    MACRO_PIN_DEFINE(PIN_BT_DATA3),
    MACRO_PIN_DEFINE(PIN_BT_DATA4),
    MACRO_PIN_DEFINE(PIN_BT_DATA5),
    MACRO_PIN_DEFINE(PIN_BT_DATA6),
    MACRO_PIN_DEFINE(PIN_BT_DATA7),

    MACRO_PIN_DEFINE(PIN_CSI0_PDN),
    MACRO_PIN_DEFINE(PIN_CSI1_PDN),
    MACRO_PIN_DEFINE(PIN_CSI0_RESET),
    MACRO_PIN_DEFINE(PIN_CSI1_RESET),

    MACRO_PIN_DEFINE(PIN_MIPI0_IIC_CLK),
    MACRO_PIN_DEFINE(PIN_MIPI0_IIC_SDA),
    MACRO_PIN_DEFINE(PIN_MIPI1_IIC_CLK),
    MACRO_PIN_DEFINE(PIN_MIPI1_IIC_SDA),
    MACRO_PIN_DEFINE(PIN_ADKEY1),
    MACRO_PIN_DEFINE(PIN_LCD_RESET),
    MACRO_PIN_DEFINE(PIN_TP_I2C_SCL),
    MACRO_PIN_DEFINE(PIN_TP_I2C_SDA),
    MACRO_PIN_DEFINE(PIN_TP_INT),
    MACRO_PIN_DEFINE(PIN_TP_RST),
    MACRO_PIN_DEFINE(PIN_DVP0_IIC_CLK),
    MACRO_PIN_DEFINE(PIN_DVP0_IIC_SDA),

    //LMAC FEM
    MACRO_PIN_DEFINE(PIN_LMAC_FEM_RF_TX_EN),
    MACRO_PIN_DEFINE(PIN_LMAC_FEM_RF_RX_EN),

    MACRO_PIN_DEFINE(PIN_SPI_PDN),
    MACRO_PIN_DEFINE(PIN_SPI_RESET),

    //IIS
    MACRO_PIN_DEFINE(PIN_IIS0_MCLK),
    MACRO_PIN_DEFINE(PIN_IIS0_BCLK),
    MACRO_PIN_DEFINE(PIN_IIS0_WCLK),
    MACRO_PIN_DEFINE(PIN_IIS0_DATA),
    MACRO_PIN_DEFINE(PIN_IIS1_MCLK),
    MACRO_PIN_DEFINE(PIN_IIS1_BCLK),
    MACRO_PIN_DEFINE(PIN_IIS1_WCLK),
    MACRO_PIN_DEFINE(PIN_IIS1_DATA),


    MACRO_PIN_DEFINE(BAT_ADC_IO),
    MACRO_PIN_DEFINE(LCD_BACKLIGHT_IO),
    MACRO_PIN_DEFINE(MUTE_PORT_IO),

    MACRO_PIN_DEFINE(PIN_MIPI_FSYNC),

    MACRO_PIN_DEFINE(PIN_IRCUT_LED),
    MACRO_PIN_DEFINE(PIN_WHITE_LED),
    MACRO_PIN_DEFINE(PIN_IRCUT_IN1),
    MACRO_PIN_DEFINE(PIN_IRCUT_IN2),
    MACRO_PIN_DEFINE(PIN_IRCUT_DETECT),
    MACRO_PIN_DEFINE(PIN_IOKEY),
    MACRO_PIN_DEFINE(PIN_POWER_KEY),

    MACRO_PIN_DEFINE(LLM_PWR_KEY_DET),
    MACRO_PIN_DEFINE(LLM_SYS_PWR_EN),

    MACRO_PIN_DEFINE(PIN_SYS_PWR_EN),
    MACRO_PIN_DEFINE(PIN_PWR_KEY_DET),
    MACRO_PIN_DEFINE(PIN_TF_PWR_EN),
    MACRO_PIN_DEFINE(PIN_AUDIO_PA_EN),
    MACRO_PIN_DEFINE(PIN_VDD_CTRL),
};
#endif
#endif